depends:
    - test-runner
    - crc

source:
    - checksum_block.c
    - cmp/cmp.c
    - serialization.c

include_directories:
    - cmp

tests:
    - tests/block_checksum_tests.cpp
    - tests/serializer_tests.cpp
    - tests/messagepack_tests.cpp
    - tests/integration_tests.cpp

